//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkPayAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Balance", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public partial class Balance : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionInfo", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public partial class TransactionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private string CommentField;
        
        private string CurrencyField;
        
        private string DateField;
        
        private decimal FeesField;
        
        private long IDField;
        
        private string InvoiceField;
        
        private decimal NetField;
        
        private string OperationNameField;
        
        private OkPayAPI.AccountInfo ReceiverField;
        
        private OkPayAPI.AccountInfo SenderField;
        
        private OkPayAPI.OperationStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fees
        {
            get
            {
                return this.FeesField;
            }
            set
            {
                this.FeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice
        {
            get
            {
                return this.InvoiceField;
            }
            set
            {
                this.InvoiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Net
        {
            get
            {
                return this.NetField;
            }
            set
            {
                this.NetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName
        {
            get
            {
                return this.OperationNameField;
            }
            set
            {
                this.OperationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.AccountInfo Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.AccountInfo Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.OperationStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AccountIDField;
        
        private string Country_ISOField;
        
        private string EmailField;
        
        private string NameField;
        
        private OkPayLink.OkPayService.VerificationStatuses VerificationStatusField;
        
        private string WalletIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country_ISO
        {
            get
            {
                return this.Country_ISOField;
            }
            set
            {
                this.Country_ISOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayLink.OkPayService.VerificationStatuses VerificationStatus
        {
            get
            {
                return this.VerificationStatusField;
            }
            set
            {
                this.VerificationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WalletID
        {
            get
            {
                return this.WalletIDField;
            }
            set
            {
                this.WalletIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationStatus", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public enum OperationStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reversed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hold = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryInfo", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public partial class HistoryInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageCountField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private int TotalCountField;
        
        private OkPayAPI.TransactionInfo[] TransactionsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount
        {
            get
            {
                return this.PageCountField;
            }
            set
            {
                this.PageCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.TransactionInfo[] Transactions
        {
            get
            {
                return this.TransactionsField;
            }
            set
            {
                this.TransactionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Withdrawal_Info", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public partial class Withdrawal_Info : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private decimal ExchangeRateField;
        
        private decimal FeeField;
        
        private decimal GrossField;
        
        private long OperationIDField;
        
        private string PaySystemTransactionIDField;
        
        private string PaymentMethodField;
        
        private decimal PaymentMethodAmountField;
        
        private OkPayAPI.OperationStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate
        {
            get
            {
                return this.ExchangeRateField;
            }
            set
            {
                this.ExchangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee
        {
            get
            {
                return this.FeeField;
            }
            set
            {
                this.FeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gross
        {
            get
            {
                return this.GrossField;
            }
            set
            {
                this.GrossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OperationID
        {
            get
            {
                return this.OperationIDField;
            }
            set
            {
                this.OperationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaySystemTransactionID
        {
            get
            {
                return this.PaySystemTransactionIDField;
            }
            set
            {
                this.PaySystemTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentMethodAmount
        {
            get
            {
                return this.PaymentMethodAmountField;
            }
            set
            {
                this.PaymentMethodAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.OperationStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionCycleIntervals", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public enum SubscriptionCycleIntervals : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Days = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weeks = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Months = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Years = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionStatuses", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public enum SubscriptionStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressTypes", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public enum AddressTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Legal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Actual = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Postal = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreapprovedPaymentStatuses", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI")]
    public enum PreapprovedPaymentStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
    }
}
namespace OkPayLink.OkPayService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationStatuses", Namespace="http://schemas.datacontract.org/2004/07/OkPayLink.OkPayService")]
    public enum VerificationStatuses : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unverified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientStatus", Namespace="http://schemas.datacontract.org/2004/07/OkPayLink.OkPayService")]
    public enum ClientStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unregistered = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registration = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unverified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 5,
    }
}
namespace OkPayAPI.DataContract
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subscription", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI.DataContract")]
    public partial class Subscription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private OkPayAPI.AccountInfo ClientField;
        
        private string CurrencyField;
        
        private long IDField;
        
        private bool IsActiveField;
        
        private string LastPaymentDateTimeField;
        
        private string MerchantWalletIDField;
        
        private string NextPaymentDateTimeField;
        
        private decimal OutstandingBalanceField;
        
        private bool ReattemptAcumField;
        
        private int ReattemptDaysField;
        
        private int RegularCountField;
        
        private int RegularCycleField;
        
        private OkPayAPI.SubscriptionCycleIntervals RegularIntervalField;
        
        private int RegularPaymentsDoneField;
        
        private decimal RegularPriceField;
        
        private string RetryAtField;
        
        private decimal SetupPriceField;
        
        private OkPayAPI.DataContract.Address ShippingAddressField;
        
        private bool ShippingNeededField;
        
        private string StartDateTimeField;
        
        private OkPayAPI.SubscriptionStatuses StatusField;
        
        private string TitleField;
        
        private int TrialCountField;
        
        private int TrialCycleField;
        
        private OkPayAPI.SubscriptionCycleIntervals TrialIntervalField;
        
        private int TrialPaymentsDoneField;
        
        private decimal TrialPriceField;
        
        private string ValidUntilField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.AccountInfo Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPaymentDateTime
        {
            get
            {
                return this.LastPaymentDateTimeField;
            }
            set
            {
                this.LastPaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantWalletID
        {
            get
            {
                return this.MerchantWalletIDField;
            }
            set
            {
                this.MerchantWalletIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextPaymentDateTime
        {
            get
            {
                return this.NextPaymentDateTimeField;
            }
            set
            {
                this.NextPaymentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OutstandingBalance
        {
            get
            {
                return this.OutstandingBalanceField;
            }
            set
            {
                this.OutstandingBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReattemptAcum
        {
            get
            {
                return this.ReattemptAcumField;
            }
            set
            {
                this.ReattemptAcumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReattemptDays
        {
            get
            {
                return this.ReattemptDaysField;
            }
            set
            {
                this.ReattemptDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegularCount
        {
            get
            {
                return this.RegularCountField;
            }
            set
            {
                this.RegularCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegularCycle
        {
            get
            {
                return this.RegularCycleField;
            }
            set
            {
                this.RegularCycleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.SubscriptionCycleIntervals RegularInterval
        {
            get
            {
                return this.RegularIntervalField;
            }
            set
            {
                this.RegularIntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegularPaymentsDone
        {
            get
            {
                return this.RegularPaymentsDoneField;
            }
            set
            {
                this.RegularPaymentsDoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RegularPrice
        {
            get
            {
                return this.RegularPriceField;
            }
            set
            {
                this.RegularPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetryAt
        {
            get
            {
                return this.RetryAtField;
            }
            set
            {
                this.RetryAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SetupPrice
        {
            get
            {
                return this.SetupPriceField;
            }
            set
            {
                this.SetupPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.DataContract.Address ShippingAddress
        {
            get
            {
                return this.ShippingAddressField;
            }
            set
            {
                this.ShippingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShippingNeeded
        {
            get
            {
                return this.ShippingNeededField;
            }
            set
            {
                this.ShippingNeededField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.SubscriptionStatuses Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialCount
        {
            get
            {
                return this.TrialCountField;
            }
            set
            {
                this.TrialCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialCycle
        {
            get
            {
                return this.TrialCycleField;
            }
            set
            {
                this.TrialCycleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.SubscriptionCycleIntervals TrialInterval
        {
            get
            {
                return this.TrialIntervalField;
            }
            set
            {
                this.TrialIntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrialPaymentsDone
        {
            get
            {
                return this.TrialPaymentsDoneField;
            }
            set
            {
                this.TrialPaymentsDoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TrialPrice
        {
            get
            {
                return this.TrialPriceField;
            }
            set
            {
                this.TrialPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidUntil
        {
            get
            {
                return this.ValidUntilField;
            }
            set
            {
                this.ValidUntilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI.DataContract")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLineField;
        
        private string CityField;
        
        private string CountryField;
        
        private bool IsVerifiedField;
        
        private string RegionField;
        
        private OkPayAPI.AddressTypes TypeField;
        
        private string ZipCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine
        {
            get
            {
                return this.AddressLineField;
            }
            set
            {
                this.AddressLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.AddressTypes Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreapprovedPayment", Namespace="http://schemas.datacontract.org/2004/07/OkPayAPI.DataContract")]
    public partial class PreapprovedPayment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AvailableAmountField;
        
        private OkPayAPI.AccountInfo ClientField;
        
        private bool ClientPaysFeeField;
        
        private string CurrencyField;
        
        private string EndDateField;
        
        private long IDField;
        
        private string InvoiceField;
        
        private string LastPaymentDateField;
        
        private string MerchantWalletIDField;
        
        private decimal PaymentsAmountField;
        
        private int PaymentsDoneField;
        
        private string StartDateField;
        
        private OkPayAPI.PreapprovedPaymentStatuses StatusField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableAmount
        {
            get
            {
                return this.AvailableAmountField;
            }
            set
            {
                this.AvailableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.AccountInfo Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ClientPaysFee
        {
            get
            {
                return this.ClientPaysFeeField;
            }
            set
            {
                this.ClientPaysFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice
        {
            get
            {
                return this.InvoiceField;
            }
            set
            {
                this.InvoiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPaymentDate
        {
            get
            {
                return this.LastPaymentDateField;
            }
            set
            {
                this.LastPaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantWalletID
        {
            get
            {
                return this.MerchantWalletIDField;
            }
            set
            {
                this.MerchantWalletIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentsAmount
        {
            get
            {
                return this.PaymentsAmountField;
            }
            set
            {
                this.PaymentsAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentsDone
        {
            get
            {
                return this.PaymentsDoneField;
            }
            set
            {
                this.PaymentsDoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OkPayAPI.PreapprovedPaymentStatuses Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://api.okpay.com", ConfigurationName="I_OkPayAPI")]
public interface I_OkPayAPI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Get_Date_Time", ReplyAction="https://api.okpay.com/I_OkPayAPI/Get_Date_TimeResponse")]
    string Get_Date_Time();
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Wallet_Get_Balance", ReplyAction="https://api.okpay.com/I_OkPayAPI/Wallet_Get_BalanceResponse")]
    OkPayAPI.Balance[] Wallet_Get_Balance(string WalletID, string SecurityToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Wallet_Get_Currency_Balance", ReplyAction="https://api.okpay.com/I_OkPayAPI/Wallet_Get_Currency_BalanceResponse")]
    OkPayAPI.Balance Wallet_Get_Currency_Balance(string WalletID, string SecurityToken, string Currency);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Send_Money", ReplyAction="https://api.okpay.com/I_OkPayAPI/Send_MoneyResponse")]
    OkPayAPI.TransactionInfo Send_Money(string WalletID, string SecurityToken, string Receiver, string Currency, decimal Amount, string Comment, bool IsReceiverPaysFees, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Transaction_Get", ReplyAction="https://api.okpay.com/I_OkPayAPI/Transaction_GetResponse")]
    OkPayAPI.TransactionInfo Transaction_Get(string WalletID, string SecurityToken, long TxnID, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Transaction_History", ReplyAction="https://api.okpay.com/I_OkPayAPI/Transaction_HistoryResponse")]
    OkPayAPI.HistoryInfo Transaction_History(string WalletID, string SecurityToken, string From, string Till, int PageSize, int PageNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/DebitCard_Prepay", ReplyAction="https://api.okpay.com/I_OkPayAPI/DebitCard_PrepayResponse")]
    long DebitCard_Prepay(string WalletID, string SecurityToken, string Email, string Currency, bool IsCourierDelivery, string Comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Account_Check", ReplyAction="https://api.okpay.com/I_OkPayAPI/Account_CheckResponse")]
    long Account_Check(string WalletID, string SecurityToken, string Account);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Ecurrency_Calculate", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Ecurrency_CalculateResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_Ecurrency_Calculate(string WalletID, string SecurityToken, string PaymentMethod, decimal Amount, string Currency, bool FeesFromAmount);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Ecurrency", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_EcurrencyResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_Ecurrency(string WalletID, string SecurityToken, string PaymentMethod, string PaySystemAccount, decimal Amount, string Currency, bool FeesFromAmount, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Card_RU", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Card_RUResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_Card_RU(string WalletID, string SecurityToken, string CardNumber, decimal Amount, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Card_World", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_Card_WorldResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_Card_World(string WalletID, string SecurityToken, string CardNumber, string Currency, decimal Amount, string ExpiryMonth, string ExpiryYear, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_CryptoCurrency_Calculate", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_CryptoCurrency_CalculateResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_CryptoCurrency_Calculate(string WalletID, string SecurityToken, string PaymentMethod, decimal Amount, string Currency);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Withdraw_To_CryptoCurrency", ReplyAction="https://api.okpay.com/I_OkPayAPI/Withdraw_To_CryptoCurrencyResponse")]
    OkPayAPI.Withdrawal_Info Withdraw_To_CryptoCurrency(string WalletID, string SecurityToken, string PaymentMethod, string PaySystemAccount, decimal Amount, string Currency, string Invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/EX_Account_Check", ReplyAction="https://api.okpay.com/I_OkPayAPI/EX_Account_CheckResponse")]
    long EX_Account_Check(string WalletID, string SecurityToken, string Account);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/EX_Client_Check_Status", ReplyAction="https://api.okpay.com/I_OkPayAPI/EX_Client_Check_StatusResponse")]
    OkPayLink.OkPayService.ClientStatus EX_Client_Check_Status(string WalletID, string SecurityToken, string Email);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Subscription_Get", ReplyAction="https://api.okpay.com/I_OkPayAPI/Subscription_GetResponse")]
    OkPayAPI.DataContract.Subscription Subscription_Get(string WalletID, string SecurityToken, long SubscriptionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Subscriptions_Filter", ReplyAction="https://api.okpay.com/I_OkPayAPI/Subscriptions_FilterResponse")]
    OkPayAPI.DataContract.Subscription[] Subscriptions_Filter(string WalletID, string SecurityToken, string Title, string From, string Till, OkPayAPI.SubscriptionStatuses[] Statuses);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Subscription_Update", ReplyAction="https://api.okpay.com/I_OkPayAPI/Subscription_UpdateResponse")]
    OkPayAPI.DataContract.Subscription Subscription_Update(string WalletID, string SecurityToken, OkPayAPI.DataContract.Subscription Sub, string Comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/Subscription_Get_Operations", ReplyAction="https://api.okpay.com/I_OkPayAPI/Subscription_Get_OperationsResponse")]
    OkPayAPI.TransactionInfo[] Subscription_Get_Operations(string WalletID, string SecurityToken, long SubscriptionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_Get", ReplyAction="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_GetResponse")]
    OkPayAPI.DataContract.PreapprovedPayment PreapprovedPayment_Get(string WalletID, string SecurityToken, long PreapprovedPaymentID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_Charge", ReplyAction="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_ChargeResponse")]
    OkPayAPI.TransactionInfo PreapprovedPayment_Charge(string WalletID, string SecurityToken, long PreapprovedPaymentID, decimal Amount, string Comment, string Receiver);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_Cancel", ReplyAction="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_CancelResponse")]
    OkPayAPI.DataContract.PreapprovedPayment PreapprovedPayment_Cancel(string WalletID, string SecurityToken, long PreapprovedPaymentID, string Comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_Get_Operations", ReplyAction="https://api.okpay.com/I_OkPayAPI/PreapprovedPayment_Get_OperationsResponse")]
    OkPayAPI.TransactionInfo[] PreapprovedPayment_Get_Operations(string WalletID, string SecurityToken, long PreapprovedPaymentID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://api.okpay.com/I_OkPayAPI/PreapprovedPayments_Filter", ReplyAction="https://api.okpay.com/I_OkPayAPI/PreapprovedPayments_FilterResponse")]
    OkPayAPI.DataContract.PreapprovedPayment[] PreapprovedPayments_Filter(string WalletID, string SecurityToken, string Title, string Invoice, string Client, OkPayAPI.PreapprovedPaymentStatuses[] Statuses);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface I_OkPayAPIChannel : I_OkPayAPI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class I_OkPayAPIClient : System.ServiceModel.ClientBase<I_OkPayAPI>, I_OkPayAPI
{
    
    public I_OkPayAPIClient()
    {
    }
    
    public I_OkPayAPIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public I_OkPayAPIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public I_OkPayAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public I_OkPayAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Get_Date_Time()
    {
        return base.Channel.Get_Date_Time();
    }
    
    public OkPayAPI.Balance[] Wallet_Get_Balance(string WalletID, string SecurityToken)
    {
        return base.Channel.Wallet_Get_Balance(WalletID, SecurityToken);
    }
    
    public OkPayAPI.Balance Wallet_Get_Currency_Balance(string WalletID, string SecurityToken, string Currency)
    {
        return base.Channel.Wallet_Get_Currency_Balance(WalletID, SecurityToken, Currency);
    }
    
    public OkPayAPI.TransactionInfo Send_Money(string WalletID, string SecurityToken, string Receiver, string Currency, decimal Amount, string Comment, bool IsReceiverPaysFees, string Invoice)
    {
        return base.Channel.Send_Money(WalletID, SecurityToken, Receiver, Currency, Amount, Comment, IsReceiverPaysFees, Invoice);
    }
    
    public OkPayAPI.TransactionInfo Transaction_Get(string WalletID, string SecurityToken, long TxnID, string Invoice)
    {
        return base.Channel.Transaction_Get(WalletID, SecurityToken, TxnID, Invoice);
    }
    
    public OkPayAPI.HistoryInfo Transaction_History(string WalletID, string SecurityToken, string From, string Till, int PageSize, int PageNumber)
    {
        return base.Channel.Transaction_History(WalletID, SecurityToken, From, Till, PageSize, PageNumber);
    }
    
    public long DebitCard_Prepay(string WalletID, string SecurityToken, string Email, string Currency, bool IsCourierDelivery, string Comment)
    {
        return base.Channel.DebitCard_Prepay(WalletID, SecurityToken, Email, Currency, IsCourierDelivery, Comment);
    }
    
    public long Account_Check(string WalletID, string SecurityToken, string Account)
    {
        return base.Channel.Account_Check(WalletID, SecurityToken, Account);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_Ecurrency_Calculate(string WalletID, string SecurityToken, string PaymentMethod, decimal Amount, string Currency, bool FeesFromAmount)
    {
        return base.Channel.Withdraw_To_Ecurrency_Calculate(WalletID, SecurityToken, PaymentMethod, Amount, Currency, FeesFromAmount);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_Ecurrency(string WalletID, string SecurityToken, string PaymentMethod, string PaySystemAccount, decimal Amount, string Currency, bool FeesFromAmount, string Invoice)
    {
        return base.Channel.Withdraw_To_Ecurrency(WalletID, SecurityToken, PaymentMethod, PaySystemAccount, Amount, Currency, FeesFromAmount, Invoice);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_Card_RU(string WalletID, string SecurityToken, string CardNumber, decimal Amount, string Invoice)
    {
        return base.Channel.Withdraw_To_Card_RU(WalletID, SecurityToken, CardNumber, Amount, Invoice);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_Card_World(string WalletID, string SecurityToken, string CardNumber, string Currency, decimal Amount, string ExpiryMonth, string ExpiryYear, string Invoice)
    {
        return base.Channel.Withdraw_To_Card_World(WalletID, SecurityToken, CardNumber, Currency, Amount, ExpiryMonth, ExpiryYear, Invoice);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_CryptoCurrency_Calculate(string WalletID, string SecurityToken, string PaymentMethod, decimal Amount, string Currency)
    {
        return base.Channel.Withdraw_To_CryptoCurrency_Calculate(WalletID, SecurityToken, PaymentMethod, Amount, Currency);
    }
    
    public OkPayAPI.Withdrawal_Info Withdraw_To_CryptoCurrency(string WalletID, string SecurityToken, string PaymentMethod, string PaySystemAccount, decimal Amount, string Currency, string Invoice)
    {
        return base.Channel.Withdraw_To_CryptoCurrency(WalletID, SecurityToken, PaymentMethod, PaySystemAccount, Amount, Currency, Invoice);
    }
    
    public long EX_Account_Check(string WalletID, string SecurityToken, string Account)
    {
        return base.Channel.EX_Account_Check(WalletID, SecurityToken, Account);
    }
    
    public OkPayLink.OkPayService.ClientStatus EX_Client_Check_Status(string WalletID, string SecurityToken, string Email)
    {
        return base.Channel.EX_Client_Check_Status(WalletID, SecurityToken, Email);
    }
    
    public OkPayAPI.DataContract.Subscription Subscription_Get(string WalletID, string SecurityToken, long SubscriptionID)
    {
        return base.Channel.Subscription_Get(WalletID, SecurityToken, SubscriptionID);
    }
    
    public OkPayAPI.DataContract.Subscription[] Subscriptions_Filter(string WalletID, string SecurityToken, string Title, string From, string Till, OkPayAPI.SubscriptionStatuses[] Statuses)
    {
        return base.Channel.Subscriptions_Filter(WalletID, SecurityToken, Title, From, Till, Statuses);
    }
    
    public OkPayAPI.DataContract.Subscription Subscription_Update(string WalletID, string SecurityToken, OkPayAPI.DataContract.Subscription Sub, string Comment)
    {
        return base.Channel.Subscription_Update(WalletID, SecurityToken, Sub, Comment);
    }
    
    public OkPayAPI.TransactionInfo[] Subscription_Get_Operations(string WalletID, string SecurityToken, long SubscriptionID)
    {
        return base.Channel.Subscription_Get_Operations(WalletID, SecurityToken, SubscriptionID);
    }
    
    public OkPayAPI.DataContract.PreapprovedPayment PreapprovedPayment_Get(string WalletID, string SecurityToken, long PreapprovedPaymentID)
    {
        return base.Channel.PreapprovedPayment_Get(WalletID, SecurityToken, PreapprovedPaymentID);
    }
    
    public OkPayAPI.TransactionInfo PreapprovedPayment_Charge(string WalletID, string SecurityToken, long PreapprovedPaymentID, decimal Amount, string Comment, string Receiver)
    {
        return base.Channel.PreapprovedPayment_Charge(WalletID, SecurityToken, PreapprovedPaymentID, Amount, Comment, Receiver);
    }
    
    public OkPayAPI.DataContract.PreapprovedPayment PreapprovedPayment_Cancel(string WalletID, string SecurityToken, long PreapprovedPaymentID, string Comment)
    {
        return base.Channel.PreapprovedPayment_Cancel(WalletID, SecurityToken, PreapprovedPaymentID, Comment);
    }
    
    public OkPayAPI.TransactionInfo[] PreapprovedPayment_Get_Operations(string WalletID, string SecurityToken, long PreapprovedPaymentID)
    {
        return base.Channel.PreapprovedPayment_Get_Operations(WalletID, SecurityToken, PreapprovedPaymentID);
    }
    
    public OkPayAPI.DataContract.PreapprovedPayment[] PreapprovedPayments_Filter(string WalletID, string SecurityToken, string Title, string Invoice, string Client, OkPayAPI.PreapprovedPaymentStatuses[] Statuses)
    {
        return base.Channel.PreapprovedPayments_Filter(WalletID, SecurityToken, Title, Invoice, Client, Statuses);
    }
}
